openapi: 3.0.0
info:
  title: PingOne Platform API - Credentials
  description: The PingOne Platform API covering the PingONe Credentials service
  version: '2023-03-30'
externalDocs:
  url: >-
    https://apidocs.pingidentity.com/pingone/platform/v1/api/#pingone-credentials
  description: PingOne Platform API Reference - Credentials APIs
servers:
  - url: https://api.pingone.{suffix}
    description: PingOne Platform API Endpoint
components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: OAuth bearer token (see documentation)
security:
  - bearer: []
tags:
  - name: PingOne Credentials
    description: >-
      This PingOne collection contains only the REST API request examples
      without documentation. For complete documentation, go to <a
      href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
  - name: PingOne Credentials > Credential Issuers
    description: >-
      This PingOne collection contains only the REST API request examples
      without documentation. For complete documentation, go to <a
      href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
  - name: PingOne Credentials > Credential Issuance Rules
    description: >-
      This PingOne collection contains only the REST API request examples
      without documentation. For complete documentation, go to <a
      href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
  - name: PingOne Credentials > Credential Digital Wallets
    description: >-
      This PingOne collection contains only the REST API request examples
      without documentation. For complete documentation, go to <a
      href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
  - name: PingOne Credentials > Credential Digital Wallets > Digital Wallet Apps
    description: >-
      This PingOne collection contains only the REST API request examples
      without documentation. For complete documentation, go to <a
      href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
  - name: PingOne Credentials > Credential Digital Wallets > Digital Wallets
    description: >-
      This PingOne collection contains only the REST API request examples
      without documentation. For complete documentation, go to <a
      href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
  - name: PingOne Credentials > User Credentials
    description: >-
      This PingOne collection contains only the REST API request examples
      without documentation. For complete documentation, go to <a
      href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
  - name: PingOne Credentials > Credential Verifications
    description: >-
      This PingOne collection contains only the REST API request examples
      without documentation. For complete documentation, go to <a
      href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
  - name: PingOne Credentials > Credential Types
    description: >-
      This PingOne collection contains only the REST API request examples
      without documentation. For complete documentation, go to <a
      href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
paths:
  /environments/{envID}/credentialIssuerProfile:
    post:
      tags:
        - PingOne Credentials > Credential Issuers
      summary: Create Credential Issuer Profile
      operationId: createCredentialIssuerProfile
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: New Issuer with Email Template
                siteUrl: https://pingidentity.com
                customEmailTemplate: >-
                  <organization> would like to issue you a new verified
                  <card-type> card. This card will be issued to your compatible
                  wallet app. If you don’t have the app, please download it from
                  your App Store (search for wallet) and go through the initial
                  setup and then click on the link below on your mobile phone.
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - PingOne Credentials > Credential Issuers
      summary: Read Credential Issuer Profile
      operationId: readCredentialIssuerProfile
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - PingOne Credentials > Credential Issuers
      summary: Update Credential Issuer Profile
      operationId: updateCredentialIssuerProfile
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: New Issuer Name 53
                siteUrl: https://pingidentity2.com
                customEmailTemplate: >-
                  <organization> would like to issue you a new verified
                  <card-type> card. This card will be issued to your compatible
                  wallet app. If you don’t have the app, please download it from
                  your App Store and go through the initial setup and then click
                  on the link below on your mobile phone.
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /environments/{envID}/credentialTypes/{credentialTypeID}/issuanceRules:
    post:
      tags:
        - PingOne Credentials > Credential Issuance Rules
      summary: Create Credential Issuance Rule
      operationId: createCredentialIssuanceRule
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                status: ACTIVE
                digitalWalletApplication:
                  id: '{{digitalWalletApplicationID}}'
                filter:
                  populationIds:
                    - '{{popID}}'
                automation:
                  issue: PERIODIC
                  update: ON_DEMAND
                  revoke: ON_DEMAND
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
        - name: credentialTypeID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - PingOne Credentials > Credential Issuance Rules
      summary: Read All Credential Issuance Rules
      operationId: readAllCredentialIssuanceRules
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
        - name: credentialTypeID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /environments/{envID}/credentialTypes/{credentialTypeID}/issuanceRules/{credentialIssuanceRuleID}:
    get:
      tags:
        - PingOne Credentials > Credential Issuance Rules
      summary: Read One Credential Issuance Rule
      operationId: readOneCredentialIssuanceRule
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
        - name: credentialTypeID
          in: path
          schema:
            type: string
          required: true
        - name: credentialIssuanceRuleID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - PingOne Credentials > Credential Issuance Rules
      summary: Update Credential Issuance Rule
      operationId: updateCredentialIssuanceRule
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                status: ACTIVE
                digitalWalletApplication:
                  id: '{{digitalWalletApplicationID}}'
                filter:
                  populationIds:
                    - '{{popID}}'
                automation:
                  issue: ON_DEMAND
                  update: ON_DEMAND
                  revoke: ON_DEMAND
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
        - name: credentialTypeID
          in: path
          schema:
            type: string
          required: true
        - name: credentialIssuanceRuleID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - PingOne Credentials > Credential Issuance Rules
      summary: Delete Credential Issuance Rule
      operationId: deleteCredentialIssuanceRule
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
        - name: credentialTypeID
          in: path
          schema:
            type: string
          required: true
        - name: credentialIssuanceRuleID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /environments/{envID}/credentialTypes/{credentialTypeID}/issuanceRules/{credentialIssuanceRuleID}/stagedChanges:
    get:
      tags:
        - PingOne Credentials > Credential Issuance Rules
      summary: Read Credential Issuance Rule Staged Changes
      operationId: readCredentialIssuanceRuleStagedChanges
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
        - name: credentialTypeID
          in: path
          schema:
            type: string
          required: true
        - name: credentialIssuanceRuleID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - PingOne Credentials > Credential Issuance Rules
      summary: Apply Credential Issuance Rule Staged Changes
      operationId: applyCredentialIssuanceRuleStagedChanges
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                revoke:
                  - '{{userID}}'
                  - '{{userID2}}'
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/vnd.pingidentity.credentials.applyStagedChanges+json
        - name: envID
          in: path
          schema:
            type: string
          required: true
        - name: credentialTypeID
          in: path
          schema:
            type: string
          required: true
        - name: credentialIssuanceRuleID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /environments/{envID}/credentialTypes/{credentialTypeID}/issuanceRules/{credentialIssuanceRuleID}/usageCounts:
    get:
      tags:
        - PingOne Credentials > Credential Issuance Rules
      summary: Read Credential Issuance Rule Usage Counts
      operationId: readCredentialIssuanceRuleUsageCounts
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
        - name: credentialTypeID
          in: path
          schema:
            type: string
          required: true
        - name: credentialIssuanceRuleID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /environments/{envID}/credentialTypes/{credentialTypeID}/issuanceRules/{credentialIssuanceRuleID}/usageDetails:
    get:
      tags:
        - PingOne Credentials > Credential Issuance Rules
      summary: Read Credential Issuance Rule Usage Details
      operationId: readCredentialIssuanceRuleUsageDetails
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
        - name: credentialTypeID
          in: path
          schema:
            type: string
          required: true
        - name: credentialIssuanceRuleID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /environments/{envID}/digitalWalletApplications:
    post:
      tags:
        - PingOne Credentials > Credential Digital Wallets > Digital Wallet Apps
      summary: Create Digital Wallet App
      operationId: createDigitalWalletApp
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Customer Wallet App
                application:
                  id: '{{applicationID}}'
                appOpenUrl: https://credentials.customer.com
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - PingOne Credentials > Credential Digital Wallets > Digital Wallet Apps
      summary: Read All Digital Wallet Apps
      operationId: readAllDigitalWalletApps
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /environments/{envID}/digitalWalletApplications/{digitalWalletApplicationID}:
    get:
      tags:
        - PingOne Credentials > Credential Digital Wallets > Digital Wallet Apps
      summary: Read One Digital Wallet App
      operationId: readOneDigitalWalletApp
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
        - name: digitalWalletApplicationID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - PingOne Credentials > Credential Digital Wallets > Digital Wallet Apps
      summary: Update Digital Wallet App
      operationId: updateDigitalWalletApp
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Fine Wallet App
                application:
                  id: '{{applicationID}}'
                appOpenUrl: https://credentials.customer.com
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
        - name: digitalWalletApplicationID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - PingOne Credentials > Credential Digital Wallets > Digital Wallet Apps
      summary: Delete Digital Wallet App
      operationId: deleteDigitalWalletApp
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
        - name: digitalWalletApplicationID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /environments/{envID}/users/{userID}/digitalWallets:
    post:
      tags:
        - PingOne Credentials > Credential Digital Wallets > Digital Wallets
      summary: Create Digital Wallet
      operationId: createDigitalWallet
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                digitalWalletApplication:
                  id: '{{digitalWalletApplicationID}}'
                notification:
                  methods:
                    - EMAIL
                    - SMS
                  template:
                    locale: en
                    variant: variant_B
                    variables: {}
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
        - name: userID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - PingOne Credentials > Credential Digital Wallets > Digital Wallets
      summary: Read All Digital Wallets
      operationId: readAllDigitalWallets
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
        - name: userID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /environments/{envID}/users/{userID}/digitalWallets/{digitalWalletID}:
    get:
      tags:
        - PingOne Credentials > Credential Digital Wallets > Digital Wallets
      summary: Read One Digital Wallet
      operationId: readOneDigitalWallet
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
        - name: userID
          in: path
          schema:
            type: string
          required: true
        - name: digitalWalletID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - PingOne Credentials > Credential Digital Wallets > Digital Wallets
      summary: Update Digital Wallet
      operationId: updateDigitalWallet
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                status: DISABLED
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
        - name: userID
          in: path
          schema:
            type: string
          required: true
        - name: digitalWalletID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - PingOne Credentials > Credential Digital Wallets > Digital Wallets
      summary: Delete Digital Wallet
      operationId: deleteDigitalWallet
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
        - name: userID
          in: path
          schema:
            type: string
          required: true
        - name: digitalWalletID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /environments/{envID}/users/{userID}/digitalWallets/{digitalWalletID}/provisionedCredentials:
    get:
      tags:
        - PingOne Credentials > Credential Digital Wallets > Digital Wallets
      summary: Read One Digital Wallet Credentials
      operationId: readOneDigitalWalletCredentials
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
        - name: userID
          in: path
          schema:
            type: string
          required: true
        - name: digitalWalletID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /environments/{envID}/users/{userID}/credentials:
    post:
      tags:
        - PingOne Credentials > User Credentials
      summary: Create a User Credential
      operationId: createAUserCredential
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                credentialType:
                  id: '{{credentialTypeID}}'
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
        - name: userID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - PingOne Credentials > User Credentials
      summary: Read All User Credentials
      operationId: readAllUserCredentials
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
        - name: userID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /environments/{envID}/users/{userID}/credentials/{credentialID}:
    get:
      tags:
        - PingOne Credentials > User Credentials
      summary: Read One User Credential
      operationId: readOneUserCredential
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
        - name: userID
          in: path
          schema:
            type: string
          required: true
        - name: credentialID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - PingOne Credentials > User Credentials
      summary: Update a User Credential
      operationId: updateAUserCredential
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                expiresAt: '2024-01-01T00:00:00.000Z'
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
        - name: userID
          in: path
          schema:
            type: string
          required: true
        - name: credentialID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /environments/{envID}/users/{userID}/credentials/{credentialID}/provisionedCredentials:
    get:
      tags:
        - PingOne Credentials > User Credentials
      summary: Read One User Credential Wallets
      operationId: readOneUserCredentialWallets
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
        - name: userID
          in: path
          schema:
            type: string
          required: true
        - name: credentialID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /environments/{envID}/presentationSessions:
    post:
      tags:
        - PingOne Credentials > Credential Verifications
      summary: Create Credential Verification Presentation Session (NATIVE)
      operationId: createCredentialVerificationPresentationSessionNative
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                message: Some custom message for the user.
                protocol: NATIVE
                requestedCredentials:
                  - type: VerifiedEmployee
                    keys:
                      - id
                  - type: Trusted Partner
                    keys:
                      - givenName
                issuerFilter:
                  environmentIds:
                    - a41aa672-204a-49b9-953d-b1f50c1b081b
                    - 3258433d-f760-422d-8716-5a8f6a7d25d9
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /environments/{envID}/presentationSessions/{credentialsVerificationID}:
    get:
      tags:
        - PingOne Credentials > Credential Verifications
      summary: Read One Credential Verification Status
      operationId: readOneCredentialVerificationStatus
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
        - name: credentialsVerificationID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /environments/{envID}/presentationSessions/{credentialsVerificationID}/credentialData:
    get:
      tags:
        - PingOne Credentials > Credential Verifications
      summary: Read Credential Verification Credential Data
      operationId: readCredentialVerificationCredentialData
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
        - name: credentialsVerificationID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /environments/{envID}/credentialTypes:
    post:
      tags:
        - PingOne Credentials > Credential Types
      summary: Create Credential Type
      operationId: createCredentialType
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                title: Wallet Developers
                description: PingOne Credentials
                issuerName: WalletDevInc
                cardType: Driver License
                metadata:
                  logoImage: ''
                  backgroundImage: >-
                    data:image/jpeg;base64,R0lGODlhIAAgAPEAAAAAAAAAM8wzMwAAACH/C05FVFNDQVBFMi4wAwEAAAAh+QQJCgABACwAAAAAIAAgAAACc4yPqcvtD6OcNIiLsxZg7o91EgiKShYA6sq27Ymm7swumsHRLgfHOXuZ8RKkn6YVHBU3pscRUIRGntDSxSJoZICfzoZBLWFjvRBJdLMtQ4d0edkkE9dJDz1bQXzyNiK/1/bXRoaRd2d4SHGHJ0gi+Ai5UAAAOw==
                  name: Wallet Developers
                  description: PingOne Credentials
                  cardColor: '#FFFFFF'
                  bgOpacityPercent: 20
                  fields:
                    - id: Alphanumeric Text -> Logo
                      title: Logo
                      isVisible: true
                      type: Alphanumeric Text
                      value: >-
                        R0lGODlhIAAgAPEAAAAAAAAAM8wzMwAAACH/C05FVFNDQVBFMi4wAwEAAAAh/jpQaW5neSBQaW5neSBQaW5neSBQaW5neQpQSU5HWSBQSU5HWSBQSU5HWSAKUElOR1lQSU5HWVBJTkdZACH5BAkKAAEALAAAAAAgACAAAAKDjI+py+0Po5wSiIuzFtPufx0Z44GbOCbAyrauG2jLS8OxrAo1zd0pYuHpXJyQw0PMsH6Nkgn30D0vK0xE+lwaowHnprVVhEJejbYnTpXNTAR0DWK8p22U1QD/oOzo7vPG1+dwYjAGxbUQJyHodjgYluD4eJdGYSJmqUgRqbnp+QkaUAAAOw==
                    - id: Directory Attribute -> Street Address
                      title: Street Address
                      isVisible: true
                      type: Directory Attribute
                      attribute: streetAddress
                    - id: Directory Attribute -> City
                      title: City
                      isVisible: true
                      type: Directory Attribute
                      attribute: locality
                    - id: Directory Attribute -> State
                      title: State
                      isVisible: true
                      type: Directory Attribute
                      attribute: region
                    - id: Directory Attribute -> Zip Code
                      title: Zip Code
                      isVisible: true
                      type: Directory Attribute
                      attribute: postalCode
                  textColor: '#000000'
                  version: 4
                cardDesignTemplate: >-
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 740
                  480"><g><rect fill="none" width="736" height="476"
                  stroke="#808993" stroke-width="3" rx="10" ry="10" x="2"
                  y="2"></rect><rect fill="${cardColor}" height="476" rx="10"
                  ry="10" width="736" x="2" y="2"></rect><image
                  href="${backgroundImage}" opacity="${bgOpacityPercent}"
                  height="476" rx="10" ry="10" width="736" x="2"
                  y="2"></image><text fill="${textColor}" font-weight="450"
                  font-size="30" x="160" y="80">${cardTitle}</text><text
                  fill="${textColor}" font-size="25" font-weight="300" x="160"
                  y="120">${cardSubtitle}</text><image href="${logoImage}"
                  x="42" y="43" height="90px" width="90px"></image><line
                  xmlns="http://www.w3.org/2000/svg" y2="160" x2="695" y1="160"
                  x1="42.5" stroke="#808993"></line><image
                  href="data:image/jpeg;base64,${fields[0].value}" x="42.5"
                  y="180" rx="80px" ry="80px" height="130px"
                  width="130px"></image><text fill="${textColor}"
                  font-weight="500" font-size="20" x="190"
                  y="230">${fields[1].title}: ${fields[1].value}</text><text
                  fill="${textColor}" font-weight="500" font-size="20" x="190"
                  y="272">${fields[2].title}: ${fields[2].value}</text><text
                  fill="${textColor}" font-weight="500" font-size="20" x="190"
                  y="314">${fields[3].title}: ${fields[3].value}</text><text
                  fill="${textColor}" font-weight="500" font-size="20" x="190"
                  y="356">${fields[4].title}:
                  ${fields[4].value}</text></g></svg>
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - PingOne Credentials > Credential Types
      summary: Read All Credential Types
      operationId: readAllCredentialTypes
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /environments/{envID}/credentialTypes/{credentialTypeID}:
    get:
      tags:
        - PingOne Credentials > Credential Types
      summary: Read One Credential Type
      operationId: readOneCredentialType
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
        - name: credentialTypeID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - PingOne Credentials > Credential Types
      summary: Update a Credential Type
      operationId: updateACredentialType
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                title: Credential type title
                description: Credential type description
                metadata:
                  name: Credential type title
                  description: Credential type description
                  textColor: '#000000'
                  cardColor: '#FFFFFF'
                  backgroundImage: ''
                  logoImage: ''
                  fields:
                    - id: Alphanumeric Text -> Logo
                      title: Logo
                      isVisible: true
                      type: Alphanumeric Text
                      value: >-
                        R0lGODlhIAAgAPEAAAAAAAAAM8wzMwAAACH/C05FVFNDQVBFMi4wAwEAAAAh/jpQaW5neSBQaW5neSBQaW5neSBQaW5neQpQSU5HWSBQSU5HWSBQSU5HWSAKUElOR1lQSU5HWVBJTkdZACH5BAkKAAEALAAAAAAgACAAAAKDjI+py+0Po5wSiIuzFtPufx0Z44GbOCbAyrauG2jLS8OxrAo1zd0pYuHpXJyQw0PMsH6Nkgn30D0vK0xE+lwaowHnprVVhEJejbYnTpXNTAR0DWK8p22U1QD/oOzo7vPG1+dwYjAGxbUQJyHodjgYluD4eJdGYSJmqUgRqbnp+QkaUAAAOw==
                    - id: Directory Attribute -> Street Address
                      title: Street Address
                      isVisible: true
                      type: Directory Attribute
                      attribute: streetAddress
                    - id: Directory Attribute -> City
                      title: City
                      isVisible: true
                      type: Directory Attribute
                      attribute: locality
                    - id: Directory Attribute -> State
                      title: State
                      isVisible: true
                      type: Directory Attribute
                      attribute: region
                    - id: Directory Attribute -> Zip Code
                      title: Zip Code
                      isVisible: true
                      type: Directory Attribute
                      attribute: postalCode
                  bgOpacityPercent: 20
                cardDesignTemplate: >-
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 740
                  480"><g><rect fill="none" width="736" height="476"
                  stroke="#808993" stroke-width="3" rx="10" ry="10" x="2"
                  y="2"></rect><rect fill="${cardColor}" height="476" rx="10"
                  ry="10" width="736" x="2" y="2"></rect><image
                  href="${backgroundImage}" opacity="${bgOpacityPercent}"
                  height="476" rx="10" ry="10" width="736" x="2"
                  y="2"></image><text fill="${textColor}" font-weight="450"
                  font-size="30" x="160" y="80">${cardTitle}</text><text
                  fill="${textColor}" font-size="25" font-weight="300" x="160"
                  y="120">${cardSubtitle}</text><image href="${logoImage}"
                  x="42" y="43" height="90px" width="90px"></image><line
                  xmlns="http://www.w3.org/2000/svg" y2="160" x2="695" y1="160"
                  x1="42.5" stroke="#808993"></line><text fill="${textColor}"
                  font-weight="500" font-size="20" x="190"
                  y="230">${fields[0].title}: ${fields[0].value}</text><text
                  fill="${textColor}" font-weight="500" font-size="20" x="190"
                  y="272">${fields[1].title}:
                  ${fields[1].value}</text></g></svg>
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
        - name: credentialTypeID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - PingOne Credentials > Credential Types
      summary: Delete a Credential Type
      operationId: deleteACredentialType
      description: >-
        This PingOne collection contains only the REST API request examples
        without documentation. For complete documentation, go to <a
        href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{jwtToken}}
        - name: envID
          in: path
          schema:
            type: string
          required: true
        - name: credentialTypeID
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
