openapi: 3.0.0
info:
  description: The PingOne Platform API covering the PingOne Credentials service
  title: PingOne Platform API - Credentials
  version: 2023-03-30
externalDocs:
  description: PingOne Platform API Reference - Credentials APIs
  url: https://apidocs.pingidentity.com/pingone/platform/v1/api/#pingone-credentials
servers:
- description: PingOne Platform API Endpoint
  url: "https://api.pingone.{suffix}"
  variables:
    suffix:
      default: com
      enum:
      - eu
      - com
      - asia
      - ca
security:
- bearer: []
tags:
- name: PingOne Credentials
- name: PingOne Credentials > Credential Issuers
- name: PingOne Credentials > Credential Issuance Rules
- name: PingOne Credentials > Credential Digital Wallets
- name: PingOne Credentials > Credential Digital Wallets > Digital Wallet Apps
- name: PingOne Credentials > Credential Digital Wallets > Digital Wallets
- name: PingOne Credentials > User Credentials
- name: PingOne Credentials > Credential Verifications
- name: PingOne Credentials > Credential Types
paths:
  /environments/{environmentID}/credentialIssuerProfile:
    get:
      operationId: readCredentialIssuerProfile
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: "Invalid request received.  Malformed JSON, malformed HTTP\
            \ request."
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request failed due to authorization issue.
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request failed due to authorization issue.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Not found.
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request was rate limited
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Uncaught error occurred.  Platform outage
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CredentialIssuerProfile'
          description: Successful response
      summary: Read Credential Issuer Profile
      tags:
      - PingOne Credentials > Credential Issuers
    post:
      operationId: createCredentialIssuerProfile
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CredentialIssuerProfile'
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: "Invalid request received.  Malformed JSON, malformed HTTP\
            \ request."
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request failed due to authorization issue.
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request failed due to authorization issue.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Not found.
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request was rate limited
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Uncaught error occurred.  Platform outage
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CredentialIssuerProfile'
          description: Successful response
      summary: Create Credential Issuer Profile
      tags:
      - PingOne Credentials > Credential Issuers
    put:
      operationId: updateCredentialIssuerProfile
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CredentialIssuerProfile'
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: "Invalid request received.  Malformed JSON, malformed HTTP\
            \ request."
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request failed due to authorization issue.
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request failed due to authorization issue.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Not found.
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request was rate limited
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Uncaught error occurred.  Platform outage
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CredentialIssuerProfile'
          description: Successful response
      summary: Update Credential Issuer Profile
      tags:
      - PingOne Credentials > Credential Issuers
  /environments/{environmentID}/credentialTypes/{credentialTypeID}/issuanceRules:
    get:
      description: "This PingOne collection contains only the REST API request examples\
        \ without documentation. For complete documentation, go to <a href=\"https://apidocs.pingidentity.com/pingone/platform/v1/api/\"\
        >apidocs.pingidentity.com</a>."
      operationId: readAllCredentialIssuanceRules
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: credentialTypeID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Read All Credential Issuance Rules
      tags:
      - PingOne Credentials > Credential Issuance Rules
    post:
      description: "This PingOne collection contains only the REST API request examples\
        \ without documentation. For complete documentation, go to <a href=\"https://apidocs.pingidentity.com/pingone/platform/v1/api/\"\
        >apidocs.pingidentity.com</a>."
      operationId: createCredentialIssuanceRule
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: credentialTypeID
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              example:
                status: ACTIVE
                digitalWalletApplication:
                  id: "{{digitalWalletApplicationID}}"
                filter:
                  populationIds:
                  - "{{popID}}"
                automation:
                  issue: PERIODIC
                  update: ON_DEMAND
                  revoke: ON_DEMAND
              type: object
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Create Credential Issuance Rule
      tags:
      - PingOne Credentials > Credential Issuance Rules
  /environments/{environmentID}/credentialTypes/{credentialTypeID}/issuanceRules/{credentialIssuanceRuleID}:
    delete:
      description: "This PingOne collection contains only the REST API request examples\
        \ without documentation. For complete documentation, go to <a href=\"https://apidocs.pingidentity.com/pingone/platform/v1/api/\"\
        >apidocs.pingidentity.com</a>."
      operationId: deleteCredentialIssuanceRule
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: credentialTypeID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: credentialIssuanceRuleID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Delete Credential Issuance Rule
      tags:
      - PingOne Credentials > Credential Issuance Rules
    get:
      description: "This PingOne collection contains only the REST API request examples\
        \ without documentation. For complete documentation, go to <a href=\"https://apidocs.pingidentity.com/pingone/platform/v1/api/\"\
        >apidocs.pingidentity.com</a>."
      operationId: readOneCredentialIssuanceRule
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: credentialTypeID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: credentialIssuanceRuleID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Read One Credential Issuance Rule
      tags:
      - PingOne Credentials > Credential Issuance Rules
    put:
      description: "This PingOne collection contains only the REST API request examples\
        \ without documentation. For complete documentation, go to <a href=\"https://apidocs.pingidentity.com/pingone/platform/v1/api/\"\
        >apidocs.pingidentity.com</a>."
      operationId: updateCredentialIssuanceRule
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: credentialTypeID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: credentialIssuanceRuleID
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              example:
                status: ACTIVE
                digitalWalletApplication:
                  id: "{{digitalWalletApplicationID}}"
                filter:
                  populationIds:
                  - "{{popID}}"
                automation:
                  issue: ON_DEMAND
                  update: ON_DEMAND
                  revoke: ON_DEMAND
              type: object
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Update Credential Issuance Rule
      tags:
      - PingOne Credentials > Credential Issuance Rules
  /environments/{environmentID}/credentialTypes/{credentialTypeID}/issuanceRules/{credentialIssuanceRuleID}/stagedChanges:
    get:
      description: "This PingOne collection contains only the REST API request examples\
        \ without documentation. For complete documentation, go to <a href=\"https://apidocs.pingidentity.com/pingone/platform/v1/api/\"\
        >apidocs.pingidentity.com</a>."
      operationId: readCredentialIssuanceRuleStagedChanges
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: credentialTypeID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: credentialIssuanceRuleID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Read Credential Issuance Rule Staged Changes
      tags:
      - PingOne Credentials > Credential Issuance Rules
    post:
      description: "This PingOne collection contains only the REST API request examples\
        \ without documentation. For complete documentation, go to <a href=\"https://apidocs.pingidentity.com/pingone/platform/v1/api/\"\
        >apidocs.pingidentity.com</a>."
      operationId: applyCredentialIssuanceRuleStagedChanges
      parameters:
      - example: application/vnd.pingidentity.credentials.applyStagedChanges+json
        explode: false
        in: header
        name: Content-Type
        required: false
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: credentialTypeID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: credentialIssuanceRuleID
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              example:
                revoke:
                - "{{userID}}"
                - "{{userID2}}"
              type: object
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Apply Credential Issuance Rule Staged Changes
      tags:
      - PingOne Credentials > Credential Issuance Rules
  /environments/{environmentID}/credentialTypes/{credentialTypeID}/issuanceRules/{credentialIssuanceRuleID}/usageCounts:
    get:
      description: "This PingOne collection contains only the REST API request examples\
        \ without documentation. For complete documentation, go to <a href=\"https://apidocs.pingidentity.com/pingone/platform/v1/api/\"\
        >apidocs.pingidentity.com</a>."
      operationId: readCredentialIssuanceRuleUsageCounts
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: credentialTypeID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: credentialIssuanceRuleID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Read Credential Issuance Rule Usage Counts
      tags:
      - PingOne Credentials > Credential Issuance Rules
  /environments/{environmentID}/credentialTypes/{credentialTypeID}/issuanceRules/{credentialIssuanceRuleID}/usageDetails:
    get:
      description: "This PingOne collection contains only the REST API request examples\
        \ without documentation. For complete documentation, go to <a href=\"https://apidocs.pingidentity.com/pingone/platform/v1/api/\"\
        >apidocs.pingidentity.com</a>."
      operationId: readCredentialIssuanceRuleUsageDetails
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: credentialTypeID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: credentialIssuanceRuleID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Read Credential Issuance Rule Usage Details
      tags:
      - PingOne Credentials > Credential Issuance Rules
  /environments/{environmentID}/digitalWalletApplications:
    get:
      description: "This PingOne collection contains only the REST API request examples\
        \ without documentation. For complete documentation, go to <a href=\"https://apidocs.pingidentity.com/pingone/platform/v1/api/\"\
        >apidocs.pingidentity.com</a>."
      operationId: readAllDigitalWalletApps
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Read All Digital Wallet Apps
      tags:
      - PingOne Credentials > Credential Digital Wallets > Digital Wallet Apps
    post:
      description: "This PingOne collection contains only the REST API request examples\
        \ without documentation. For complete documentation, go to <a href=\"https://apidocs.pingidentity.com/pingone/platform/v1/api/\"\
        >apidocs.pingidentity.com</a>."
      operationId: createDigitalWalletApp
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              example:
                name: Customer Wallet App
                application:
                  id: "{{applicationID}}"
                appOpenUrl: https://credentials.customer.com
              type: object
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Create Digital Wallet App
      tags:
      - PingOne Credentials > Credential Digital Wallets > Digital Wallet Apps
  /environments/{environmentID}/digitalWalletApplications/{digitalWalletApplicationID}:
    delete:
      description: "This PingOne collection contains only the REST API request examples\
        \ without documentation. For complete documentation, go to <a href=\"https://apidocs.pingidentity.com/pingone/platform/v1/api/\"\
        >apidocs.pingidentity.com</a>."
      operationId: deleteDigitalWalletApp
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: digitalWalletApplicationID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Delete Digital Wallet App
      tags:
      - PingOne Credentials > Credential Digital Wallets > Digital Wallet Apps
    get:
      description: "This PingOne collection contains only the REST API request examples\
        \ without documentation. For complete documentation, go to <a href=\"https://apidocs.pingidentity.com/pingone/platform/v1/api/\"\
        >apidocs.pingidentity.com</a>."
      operationId: readOneDigitalWalletApp
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: digitalWalletApplicationID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Read One Digital Wallet App
      tags:
      - PingOne Credentials > Credential Digital Wallets > Digital Wallet Apps
    put:
      description: "This PingOne collection contains only the REST API request examples\
        \ without documentation. For complete documentation, go to <a href=\"https://apidocs.pingidentity.com/pingone/platform/v1/api/\"\
        >apidocs.pingidentity.com</a>."
      operationId: updateDigitalWalletApp
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: digitalWalletApplicationID
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              example:
                name: Fine Wallet App
                application:
                  id: "{{applicationID}}"
                appOpenUrl: https://credentials.customer.com
              type: object
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Update Digital Wallet App
      tags:
      - PingOne Credentials > Credential Digital Wallets > Digital Wallet Apps
  /environments/{environmentID}/users/{userID}/digitalWallets:
    get:
      description: "This PingOne collection contains only the REST API request examples\
        \ without documentation. For complete documentation, go to <a href=\"https://apidocs.pingidentity.com/pingone/platform/v1/api/\"\
        >apidocs.pingidentity.com</a>."
      operationId: readAllDigitalWallets
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: userID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Read All Digital Wallets
      tags:
      - PingOne Credentials > Credential Digital Wallets > Digital Wallets
    post:
      description: "This PingOne collection contains only the REST API request examples\
        \ without documentation. For complete documentation, go to <a href=\"https://apidocs.pingidentity.com/pingone/platform/v1/api/\"\
        >apidocs.pingidentity.com</a>."
      operationId: createDigitalWallet
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: userID
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              example:
                digitalWalletApplication:
                  id: "{{digitalWalletApplicationID}}"
                notification:
                  methods:
                  - EMAIL
                  - SMS
                  template:
                    locale: en
                    variant: variant_B
                    variables: {}
              type: object
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Create Digital Wallet
      tags:
      - PingOne Credentials > Credential Digital Wallets > Digital Wallets
  /environments/{environmentID}/users/{userID}/digitalWallets/{digitalWalletID}:
    delete:
      description: "This PingOne collection contains only the REST API request examples\
        \ without documentation. For complete documentation, go to <a href=\"https://apidocs.pingidentity.com/pingone/platform/v1/api/\"\
        >apidocs.pingidentity.com</a>."
      operationId: deleteDigitalWallet
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: userID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: digitalWalletID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Delete Digital Wallet
      tags:
      - PingOne Credentials > Credential Digital Wallets > Digital Wallets
    get:
      description: "This PingOne collection contains only the REST API request examples\
        \ without documentation. For complete documentation, go to <a href=\"https://apidocs.pingidentity.com/pingone/platform/v1/api/\"\
        >apidocs.pingidentity.com</a>."
      operationId: readOneDigitalWallet
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: userID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: digitalWalletID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Read One Digital Wallet
      tags:
      - PingOne Credentials > Credential Digital Wallets > Digital Wallets
    put:
      description: "This PingOne collection contains only the REST API request examples\
        \ without documentation. For complete documentation, go to <a href=\"https://apidocs.pingidentity.com/pingone/platform/v1/api/\"\
        >apidocs.pingidentity.com</a>."
      operationId: updateDigitalWallet
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: userID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: digitalWalletID
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              example:
                status: DISABLED
              type: object
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Update Digital Wallet
      tags:
      - PingOne Credentials > Credential Digital Wallets > Digital Wallets
  /environments/{environmentID}/users/{userID}/digitalWallets/{digitalWalletID}/provisionedCredentials:
    get:
      description: "This PingOne collection contains only the REST API request examples\
        \ without documentation. For complete documentation, go to <a href=\"https://apidocs.pingidentity.com/pingone/platform/v1/api/\"\
        >apidocs.pingidentity.com</a>."
      operationId: readOneDigitalWalletCredentials
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: userID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: digitalWalletID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Read One Digital Wallet Credentials
      tags:
      - PingOne Credentials > Credential Digital Wallets > Digital Wallets
  /environments/{environmentID}/users/{userID}/credentials:
    get:
      description: "This PingOne collection contains only the REST API request examples\
        \ without documentation. For complete documentation, go to <a href=\"https://apidocs.pingidentity.com/pingone/platform/v1/api/\"\
        >apidocs.pingidentity.com</a>."
      operationId: readAllUserCredentials
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: userID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Read All User Credentials
      tags:
      - PingOne Credentials > User Credentials
    post:
      description: "This PingOne collection contains only the REST API request examples\
        \ without documentation. For complete documentation, go to <a href=\"https://apidocs.pingidentity.com/pingone/platform/v1/api/\"\
        >apidocs.pingidentity.com</a>."
      operationId: createAUserCredential
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: userID
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              example:
                credentialType:
                  id: "{{credentialTypeID}}"
              type: object
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Create a User Credential
      tags:
      - PingOne Credentials > User Credentials
  /environments/{environmentID}/users/{userID}/credentials/{credentialID}:
    get:
      description: "This PingOne collection contains only the REST API request examples\
        \ without documentation. For complete documentation, go to <a href=\"https://apidocs.pingidentity.com/pingone/platform/v1/api/\"\
        >apidocs.pingidentity.com</a>."
      operationId: readOneUserCredential
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: userID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: credentialID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Read One User Credential
      tags:
      - PingOne Credentials > User Credentials
    put:
      description: "This PingOne collection contains only the REST API request examples\
        \ without documentation. For complete documentation, go to <a href=\"https://apidocs.pingidentity.com/pingone/platform/v1/api/\"\
        >apidocs.pingidentity.com</a>."
      operationId: updateAUserCredential
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: userID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: credentialID
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              example:
                expiresAt: 2024-01-01T00:00:00.000Z
              type: object
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Update a User Credential
      tags:
      - PingOne Credentials > User Credentials
  /environments/{environmentID}/users/{userID}/credentials/{credentialID}/provisionedCredentials:
    get:
      description: "This PingOne collection contains only the REST API request examples\
        \ without documentation. For complete documentation, go to <a href=\"https://apidocs.pingidentity.com/pingone/platform/v1/api/\"\
        >apidocs.pingidentity.com</a>."
      operationId: readOneUserCredentialWallets
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: userID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: credentialID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Read One User Credential Wallets
      tags:
      - PingOne Credentials > User Credentials
  /environments/{environmentID}/presentationSessions:
    post:
      description: "This PingOne collection contains only the REST API request examples\
        \ without documentation. For complete documentation, go to <a href=\"https://apidocs.pingidentity.com/pingone/platform/v1/api/\"\
        >apidocs.pingidentity.com</a>."
      operationId: createCredentialVerificationPresentationSessionNative
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              example:
                message: Some custom message for the user.
                protocol: NATIVE
                requestedCredentials:
                - type: VerifiedEmployee
                  keys:
                  - id
                - type: Trusted Partner
                  keys:
                  - givenName
                issuerFilter:
                  environmentIds:
                  - a41aa672-204a-49b9-953d-b1f50c1b081b
                  - 3258433d-f760-422d-8716-5a8f6a7d25d9
              type: object
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Create Credential Verification Presentation Session (NATIVE)
      tags:
      - PingOne Credentials > Credential Verifications
  /environments/{environmentID}/presentationSessions/{credentialsVerificationID}:
    get:
      description: "This PingOne collection contains only the REST API request examples\
        \ without documentation. For complete documentation, go to <a href=\"https://apidocs.pingidentity.com/pingone/platform/v1/api/\"\
        >apidocs.pingidentity.com</a>."
      operationId: readOneCredentialVerificationStatus
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: credentialsVerificationID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Read One Credential Verification Status
      tags:
      - PingOne Credentials > Credential Verifications
  /environments/{environmentID}/presentationSessions/{credentialsVerificationID}/credentialData:
    get:
      description: "This PingOne collection contains only the REST API request examples\
        \ without documentation. For complete documentation, go to <a href=\"https://apidocs.pingidentity.com/pingone/platform/v1/api/\"\
        >apidocs.pingidentity.com</a>."
      operationId: readCredentialVerificationCredentialData
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: credentialsVerificationID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Read Credential Verification Credential Data
      tags:
      - PingOne Credentials > Credential Verifications
  /environments/{environmentID}/credentialTypes:
    get:
      description: "This PingOne collection contains only the REST API request examples\
        \ without documentation. For complete documentation, go to <a href=\"https://apidocs.pingidentity.com/pingone/platform/v1/api/\"\
        >apidocs.pingidentity.com</a>."
      operationId: readAllCredentialTypes
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Read All Credential Types
      tags:
      - PingOne Credentials > Credential Types
    post:
      description: "This PingOne collection contains only the REST API request examples\
        \ without documentation. For complete documentation, go to <a href=\"https://apidocs.pingidentity.com/pingone/platform/v1/api/\"\
        >apidocs.pingidentity.com</a>."
      operationId: createCredentialType
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              example:
                title: Wallet Developers
                description: PingOne Credentials
                issuerName: WalletDevInc
                cardType: Driver License
                metadata:
                  logoImage: ""
                  backgroundImage: "data:image/jpeg;base64,R0lGODlhIAAgAPEAAAAAAAAAM8wzMwAAACH/C05FVFNDQVBFMi4wAwEAAAAh+QQJCgABACwAAAAAIAAgAAACc4yPqcvtD6OcNIiLsxZg7o91EgiKShYA6sq27Ymm7swumsHRLgfHOXuZ8RKkn6YVHBU3pscRUIRGntDSxSJoZICfzoZBLWFjvRBJdLMtQ4d0edkkE9dJDz1bQXzyNiK/1/bXRoaRd2d4SHGHJ0gi+Ai5UAAAOw=="
                  name: Wallet Developers
                  description: PingOne Credentials
                  cardColor: '#FFFFFF'
                  bgOpacityPercent: 20
                  fields:
                  - id: Alphanumeric Text -> Logo
                    title: Logo
                    isVisible: true
                    type: Alphanumeric Text
                    value: R0lGODlhIAAgAPEAAAAAAAAAM8wzMwAAACH/C05FVFNDQVBFMi4wAwEAAAAh/jpQaW5neSBQaW5neSBQaW5neSBQaW5neQpQSU5HWSBQSU5HWSBQSU5HWSAKUElOR1lQSU5HWVBJTkdZACH5BAkKAAEALAAAAAAgACAAAAKDjI+py+0Po5wSiIuzFtPufx0Z44GbOCbAyrauG2jLS8OxrAo1zd0pYuHpXJyQw0PMsH6Nkgn30D0vK0xE+lwaowHnprVVhEJejbYnTpXNTAR0DWK8p22U1QD/oOzo7vPG1+dwYjAGxbUQJyHodjgYluD4eJdGYSJmqUgRqbnp+QkaUAAAOw==
                  - id: Directory Attribute -> Street Address
                    title: Street Address
                    isVisible: true
                    type: Directory Attribute
                    attribute: streetAddress
                  - id: Directory Attribute -> City
                    title: City
                    isVisible: true
                    type: Directory Attribute
                    attribute: locality
                  - id: Directory Attribute -> State
                    title: State
                    isVisible: true
                    type: Directory Attribute
                    attribute: region
                  - id: Directory Attribute -> Zip Code
                    title: Zip Code
                    isVisible: true
                    type: Directory Attribute
                    attribute: postalCode
                  textColor: '#000000'
                  version: 4
                cardDesignTemplate: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"\
                  0 0 740 480\"><g><rect fill=\"none\" width=\"736\" height=\"476\"\
                  \ stroke=\"#808993\" stroke-width=\"3\" rx=\"10\" ry=\"10\" x=\"\
                  2\" y=\"2\"></rect><rect fill=\"${cardColor}\" height=\"476\" rx=\"\
                  10\" ry=\"10\" width=\"736\" x=\"2\" y=\"2\"></rect><image href=\"\
                  ${backgroundImage}\" opacity=\"${bgOpacityPercent}\" height=\"476\"\
                  \ rx=\"10\" ry=\"10\" width=\"736\" x=\"2\" y=\"2\"></image><text\
                  \ fill=\"${textColor}\" font-weight=\"450\" font-size=\"30\" x=\"\
                  160\" y=\"80\">${cardTitle}</text><text fill=\"${textColor}\" font-size=\"\
                  25\" font-weight=\"300\" x=\"160\" y=\"120\">${cardSubtitle}</text><image\
                  \ href=\"${logoImage}\" x=\"42\" y=\"43\" height=\"90px\" width=\"\
                  90px\"></image><line xmlns=\"http://www.w3.org/2000/svg\" y2=\"\
                  160\" x2=\"695\" y1=\"160\" x1=\"42.5\" stroke=\"#808993\"></line><image\
                  \ href=\"data:image/jpeg;base64,${fields[0].value}\" x=\"42.5\"\
                  \ y=\"180\" rx=\"80px\" ry=\"80px\" height=\"130px\" width=\"130px\"\
                  ></image><text fill=\"${textColor}\" font-weight=\"500\" font-size=\"\
                  20\" x=\"190\" y=\"230\">${fields[1].title}: ${fields[1].value}</text><text\
                  \ fill=\"${textColor}\" font-weight=\"500\" font-size=\"20\" x=\"\
                  190\" y=\"272\">${fields[2].title}: ${fields[2].value}</text><text\
                  \ fill=\"${textColor}\" font-weight=\"500\" font-size=\"20\" x=\"\
                  190\" y=\"314\">${fields[3].title}: ${fields[3].value}</text><text\
                  \ fill=\"${textColor}\" font-weight=\"500\" font-size=\"20\" x=\"\
                  190\" y=\"356\">${fields[4].title}: ${fields[4].value}</text></g></svg>"
              type: object
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Create Credential Type
      tags:
      - PingOne Credentials > Credential Types
  /environments/{environmentID}/credentialTypes/{credentialTypeID}:
    delete:
      description: "This PingOne collection contains only the REST API request examples\
        \ without documentation. For complete documentation, go to <a href=\"https://apidocs.pingidentity.com/pingone/platform/v1/api/\"\
        >apidocs.pingidentity.com</a>."
      operationId: deleteACredentialType
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: credentialTypeID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Delete a Credential Type
      tags:
      - PingOne Credentials > Credential Types
    get:
      description: "This PingOne collection contains only the REST API request examples\
        \ without documentation. For complete documentation, go to <a href=\"https://apidocs.pingidentity.com/pingone/platform/v1/api/\"\
        >apidocs.pingidentity.com</a>."
      operationId: readOneCredentialType
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: credentialTypeID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Read One Credential Type
      tags:
      - PingOne Credentials > Credential Types
    put:
      description: "This PingOne collection contains only the REST API request examples\
        \ without documentation. For complete documentation, go to <a href=\"https://apidocs.pingidentity.com/pingone/platform/v1/api/\"\
        >apidocs.pingidentity.com</a>."
      operationId: updateACredentialType
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: credentialTypeID
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              example:
                title: Credential type title
                description: Credential type description
                metadata:
                  name: Credential type title
                  description: Credential type description
                  textColor: '#000000'
                  cardColor: '#FFFFFF'
                  backgroundImage: ""
                  logoImage: ""
                  fields:
                  - id: Alphanumeric Text -> Logo
                    title: Logo
                    isVisible: true
                    type: Alphanumeric Text
                    value: R0lGODlhIAAgAPEAAAAAAAAAM8wzMwAAACH/C05FVFNDQVBFMi4wAwEAAAAh/jpQaW5neSBQaW5neSBQaW5neSBQaW5neQpQSU5HWSBQSU5HWSBQSU5HWSAKUElOR1lQSU5HWVBJTkdZACH5BAkKAAEALAAAAAAgACAAAAKDjI+py+0Po5wSiIuzFtPufx0Z44GbOCbAyrauG2jLS8OxrAo1zd0pYuHpXJyQw0PMsH6Nkgn30D0vK0xE+lwaowHnprVVhEJejbYnTpXNTAR0DWK8p22U1QD/oOzo7vPG1+dwYjAGxbUQJyHodjgYluD4eJdGYSJmqUgRqbnp+QkaUAAAOw==
                  - id: Directory Attribute -> Street Address
                    title: Street Address
                    isVisible: true
                    type: Directory Attribute
                    attribute: streetAddress
                  - id: Directory Attribute -> City
                    title: City
                    isVisible: true
                    type: Directory Attribute
                    attribute: locality
                  - id: Directory Attribute -> State
                    title: State
                    isVisible: true
                    type: Directory Attribute
                    attribute: region
                  - id: Directory Attribute -> Zip Code
                    title: Zip Code
                    isVisible: true
                    type: Directory Attribute
                    attribute: postalCode
                  bgOpacityPercent: 20
                cardDesignTemplate: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"\
                  0 0 740 480\"><g><rect fill=\"none\" width=\"736\" height=\"476\"\
                  \ stroke=\"#808993\" stroke-width=\"3\" rx=\"10\" ry=\"10\" x=\"\
                  2\" y=\"2\"></rect><rect fill=\"${cardColor}\" height=\"476\" rx=\"\
                  10\" ry=\"10\" width=\"736\" x=\"2\" y=\"2\"></rect><image href=\"\
                  ${backgroundImage}\" opacity=\"${bgOpacityPercent}\" height=\"476\"\
                  \ rx=\"10\" ry=\"10\" width=\"736\" x=\"2\" y=\"2\"></image><text\
                  \ fill=\"${textColor}\" font-weight=\"450\" font-size=\"30\" x=\"\
                  160\" y=\"80\">${cardTitle}</text><text fill=\"${textColor}\" font-size=\"\
                  25\" font-weight=\"300\" x=\"160\" y=\"120\">${cardSubtitle}</text><image\
                  \ href=\"${logoImage}\" x=\"42\" y=\"43\" height=\"90px\" width=\"\
                  90px\"></image><line xmlns=\"http://www.w3.org/2000/svg\" y2=\"\
                  160\" x2=\"695\" y1=\"160\" x1=\"42.5\" stroke=\"#808993\"></line><text\
                  \ fill=\"${textColor}\" font-weight=\"500\" font-size=\"20\" x=\"\
                  190\" y=\"230\">${fields[0].title}: ${fields[0].value}</text><text\
                  \ fill=\"${textColor}\" font-weight=\"500\" font-size=\"20\" x=\"\
                  190\" y=\"272\">${fields[1].title}: ${fields[1].value}</text></g></svg>"
              type: object
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Update a Credential Type
      tags:
      - PingOne Credentials > Credential Types
components:
  schemas:
    CredentialIssuerProfile:
      example:
        createdAt: createdAt
        siteUrl: siteUrl
        applicationInstance:
          id: id
        name: name
        id: id
        customEmailTemplate: customEmailTemplate
        updatedAt: updatedAt
      properties:
        applicationInstance:
          $ref: '#/components/schemas/CredentialIssuerProfile_applicationInstance'
        createdAt:
          description: A string that specifies the date and time the issuer profile
            was created.
          type: string
        id:
          description: A string that specifies the identifier (UUID) of the credential
            issuer.
          type: string
        name:
          description: The name of the credential issuer. This will be included in
            credentials issued.
          type: string
        updatedAt:
          description: A string that specifies the date and time the credential issuer
            profile was last updated; can be null.
          type: string
        siteUrl:
          description: A string that specifies the base URL associated with the credential
            issuer.
          type: string
        customEmailTemplate:
          description: A string that specifies the default notification template used
            in credential issuance notifications. Deprecated.
          type: string
      required:
      - name
      type: object
    P1Error:
      properties:
        id:
          description: "A unique identifier that is stored in log files and always\
            \ included in an error response. This value can be used to track the error\
            \ received by the client, with server-side activity included for troubleshooting\
            \ purposes."
          type: string
        code:
          description: A general fault code which the client must handle to provide
            all exception handling routines and to localize messages for users. This
            code is common across all PingOne services and is human readable (such
            as a defined constant rather than a number).
          type: string
        message:
          description: A short description of the error. This message is intended
            to assist with debugging and is returned in English only.
          type: string
        details:
          description: Additional details about the error. Optional information to
            help resolve the error and to display to users.
          items:
            $ref: '#/components/schemas/P1Error_details_inner'
          type: array
      type: object
    CredentialIssuerProfile_applicationInstance:
      example:
        id: id
      properties:
        id:
          description: A string that specifies the identifier (UUID) of the application
            instance registered with the PingOne platform service.
          type: string
      required:
      - id
      type: object
    P1Error_details_inner_innerError:
      description: Additional details to help the client developer resolve the fault
        (primarily for UI validation reasons).
      properties:
        rangeMinimumValue:
          description: Errors that failed due to range violation. This attribute represents
            the minimum value of the range.
          type: integer
        rangeMaximumValue:
          description: The maximum range or value of an attribute.
          type: integer
        allowedPattern:
          description: A regex pattern describing an acceptable input pattern.
          type: string
        allowedValues:
          description: A list describing acceptable values.
          items:
            type: string
          type: array
        maximumValue:
          description: The maximum value allowed for the request.
          type: integer
      type: object
    P1Error_details_inner:
      properties:
        code:
          description: A general fault code which the client must handle to provide
            all exception handling routines and to localize messages for users. This
            code is common across all PingOne services and is human readable (such
            as a defined constant rather than a number).
          type: string
        target:
          description: The item that caused the error (such as a form field ID or
            an attribute inside a JSON object).
          type: string
        message:
          description: A short description of the error. This message is intended
            to assist with debugging and is returned in English only.
          type: string
        innerError:
          $ref: '#/components/schemas/P1Error_details_inner_innerError'
      type: object
  securitySchemes:
    bearer:
      bearerFormat: JWT
      description: OAuth bearer token (see documentation)
      scheme: bearer
      type: http
